apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeadm-config
  namespace: kube-system
data:
  ClusterConfiguration: |
    apiServer:
      extraArgs:
        - name: "enable-admission-plugins"
          value: "NodeRestriction,ImagePolicyWebhook"
        - name: "admission-control-config-file"
          value: "/etc/kubernetes/imagine/admissionconfig.yaml"
      extraVolumes:
        - name: "imagine"
          hostPath: "/etc/kubernetes/imagine"
          mountPath: "/etc/kubernetes/imagine"
          readOnly: true
          pathType: DirectoryOrCreate
    apiVersion: kubeadm.k8s.io/v1beta4
    caCertificateValidityPeriod: 87600h0m0s
    certificateValidityPeriod: 8760h0m0s
    certificatesDir: /etc/kubernetes/pki
    clusterName: kubernetes
    controlPlaneEndpoint: 192.168.10.4:6443
    controllerManager:
      extraArgs:
        - name: "allocate-node-cidrs"
          value: true
        - name: "cluster-cidr"
          value: "10.95.0.0/16"
    dns: {}
    encryptionAlgorithm: RSA-2048
    etcd:
      local:
        dataDir: /var/lib/etcd
    imageRepository: registry.k8s.io
    kind: ClusterConfiguration
    kubernetesVersion: v1.31.2
    networking:
      dnsDomain: cluster.local
      serviceSubnet: 10.96.0.0/12
    proxy: {}
    scheduler: {}
