- rule: privileged
  desc: Informational log if a container is running as privileged
  condition: >
    container and
    container.privileged=true and
    evt.type in (open, openat, write, create)
  output: >
    c=%container.id p=%k8s.pod.name ns=%k8s.ns.name file=%fd.name
  priority: INFO
