- rule: priv
  condition: >
    container and
    container.privileged=true and
    evt.type in (open, openat, write, create)
  output: >
    cid=%container.id k8s_pod=%k8s.pod.name ns=%k8s.ns.name file=%fd.name
  priority: INFO
