apiVersion: v1
kind: Namespace
metadata:
  name: priv
---
apiVersion: v1
kind: Pod
metadata:
  name: busypod
  namespace: priv
spec:
  containers:
    - name: busybox
      image: busybox:latest
      securityContext:
        privileged: false
      args:
        - "sh"
        - "-c"
        - "sleep 1d"
