apiVersion: v1
kind: Service
metadata:
  labels:
    app: team-a
  name: team-a
  namespace: team-a
spec:
  ports:
    - name: 80-80
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    team: a
  type: ClusterIP
status:
  loadBalancer: {}
