apiVersion: v1
kind: Pod
metadata:
  labels:
    team: a
  name: team-a-nginx
  namespace: team-a
spec:
  containers:
    - image: mikejoh/nginxplusplus:latest
      name: nginxplusplus
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
